#ifndef COLOR_CLASSIFIER_H
#define COLOR_CLASSIFIER_H

/*
 * color_classifier.h  —  AUTO-GENERATED by train_gate_classifier.py
 *
 * Decision tree trained on gate images (YUV color space).
 * max_depth : 4
 * Test accuracy: 0.9978
 *
 * Sklearn tree (for reference):
 * |--- U <= 160.50
 * |   |--- V <= 116.50
 * |   |   |--- Y <= 122.50
 * |   |   |   |--- U <= 158.50
 * |   |   |   |   |--- class: 0
 * |   |   |   |--- U >  158.50
 * |   |   |   |   |--- class: 0
 * |   |   |--- Y >  122.50
 * |   |   |   |--- V <= 108.50
 * |   |   |   |   |--- class: 0
 * |   |   |   |--- V >  108.50
 * |   |   |   |   |--- class: 0
 * |   |--- V >  116.50
 * |   |   |--- U <= 150.50
 * |   |   |   |--- V <= 118.50
 * |   |   |   |   |--- class: 0
 * |   |   |   |--- V >  118.50
 * |   |   |   |   |--- class: 0
 * |   |   |--- U >  150.50
 * |   |   |   |--- Y <= 135.50
 * |   |   |   |   |--- class: 0
 * |   |   |   |--- Y >  135.50
 * |   |   |   |   |--- class: 0
 * |--- U >  160.50
 * |   |--- Y <= 85.50
 * |   |   |--- V <= 82.50
 * |   |   |   |--- U <= 172.50
 * |   |   |   |   |--- class: 0
 * |   |   |   |--- U >  172.50
 * |   |   |   |   |--- class: 255
 * |   |   |--- V >  82.50
 * |   |   |   |--- Y <= 54.50
 * |   |   |   |   |--- class: 0
 * |   |   |   |--- Y >  54.50
 * |   |   |   |   |--- class: 255
 * |   |--- Y >  85.50
 * |   |   |--- V <= 110.50
 * |   |   |   |--- Y <= 95.50
 * |   |   |   |   |--- class: 255
 * |   |   |   |--- Y >  95.50
 * |   |   |   |   |--- class: 0
 * |   |   |--- V >  110.50
 * |   |   |   |--- U <= 165.50
 * |   |   |   |   |--- class: 0
 * |   |   |   |--- U >  165.50
 * |   |   |   |   |--- class: 0
 *
 * Drop-in replacement for cv::inRange() in find_contour():
 *
 *   // Before (OpenCV):
 *   inRange(M,
 *           Scalar(LOWER_Y, LOWER_U, LOWER_V),
 *           Scalar(UPPER_Y, UPPER_U, UPPER_V),
 *           thresh_image);
 *
 *   // After (this classifier):
 *   for (int r = 0; r < height; r++) {
 *     for (int c = 0; c < width; c++) {
 *       cv::Vec3b p = M.at<cv::Vec3b>(r, c);
 *       thresh_image.at<uint8_t>(r, c) =
 *           classify_yuv_pixel(p[0], p[1], p[2]);
 *     }
 *   }
 */

#include <stdint.h>

/**
 * classify_yuv_pixel() - classify one YUV pixel as gate (255) or background (0).
 * @y: Y  (luminance),  0-255
 * @u: U  (Cb chroma),  0-255
 * @v: V  (Cr chroma),  0-255
 *
 * Returns: 255 if gate, 0 if background.
 * No branches taken on average: ~4 comparisons worst-case.
 */
static inline uint8_t classify_yuv_pixel(uint8_t y, uint8_t u, uint8_t v)
{
    if (u <= 160u) {
        if (v <= 116u) {
            if (y <= 122u) {
                if (u <= 158u) {
                    return 0u;
                } else {
                    return 0u;
                }
            } else {
                if (v <= 108u) {
                    return 0u;
                } else {
                    return 0u;
                }
            }
        } else {
            if (u <= 150u) {
                if (v <= 118u) {
                    return 0u;
                } else {
                    return 0u;
                }
            } else {
                if (y <= 135u) {
                    return 0u;
                } else {
                    return 0u;
                }
            }
        }
    } else {
        if (y <= 85u) {
            if (v <= 82u) {
                if (u <= 172u) {
                    return 0u;
                } else {
                    return 1u;
                }
            } else {
                if (y <= 54u) {
                    return 0u;
                } else {
                    return 1u;
                }
            }
        } else {
            if (v <= 110u) {
                if (y <= 95u) {
                    return 1u;
                } else {
                    return 0u;
                }
            } else {
                if (u <= 165u) {
                    return 0u;
                } else {
                    return 0u;
                }
            }
        }
    }
}

/**
 * classify_yuv_image() - classify an entire YUV image into a binary mask.
 * @yuv:  pointer to H*W*3 bytes, packed [Y,U,V] per pixel (cv::COLOR_BGR2YUV layout)
 * @mask: output buffer of H*W bytes; caller must allocate. 255=gate, 0=bg.
 * @w:    image width
 * @h:    image height
 */
static inline void classify_yuv_image(const uint8_t *yuv,
                                       uint8_t       *mask,
                                       int            w,
                                       int            h)
{
    int n = w * h;
    for (int i = 0; i < n; i++) {
        mask[i] = classify_yuv_pixel(yuv[3*i], yuv[3*i+1], yuv[3*i+2]);
    }
}

#endif /* COLOR_CLASSIFIER_H */
